version: '3.8'
services:
  user-management-api:
    image: [თქვენი_image_მისამართი] # მაგ: ghcr.io/username/repo:latest
    container_name: user_management_api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      # ვიყენებთ ზუსტ სახელს: postgresql-gfww-postgresql-1
      - ConnectionStrings__Postgres_AuthServer=Host=postgresql-gfww-postgresql-1;Port=5432;Database=AuthServer;Username=admin;Password=Syllogia123
      - RabbitMqOptions__Host=erp_rabbitmq
    networks:
      - erp-common-network
    ports:
      - "5001:8080"

networks:
  erp-common-network:
    external: true
